#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.2.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

environment:
#  standard_version: '2.2.$(appveyor_build_number)'
  standard_version: '1.3.1'
  BullOak_NEventStore_Sql: "Persist Security Info=True;User ID=sa;Password=Password12!;Initial Catalog=BullOakTest;Data Source=localhost\\SQL2017"

  
before_build:
  - nuget restore ./src/BullOak.Repositories.EntityFramework.sln
  - sqlcmd -S ".\SQL2017" -U "sa" -P "Password12!" -Q "CREATE DATABASE BullOakTest"
  - ps: |
        Write-Output "env.appveyor_build_number = $env:appveyor_build_number"
        Write-Output "env.standard_version = $env:standard_version"
        Write-Output "env.file_version = $env:file_version"

# branches to build
branches:
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\BullOak.Repositories.EntityFramework

# enable service required for build/tests
services:
  - mssql2017          # start SQL Server 2017 Developer Edition
  - mongodb             # start MongoDB

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# setting up etc\hosts file
hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - libs
  - '%LocalAppData%\NuGet\Cache'

pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(standard_version)'
  assembly_version: '$(standard_version).$(appveyor_build_number)'
  file_version: '$(standard_version).$(appveyor_build_number)'
  

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\BullOak.Repositories.EntityFramework.sln      # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  verbosity: normal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**\*.Test.Unit.dll'
    - '**\*.Test.Acceptance.dll'
    - '**\*.Test.Integration.dll'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '*.nupkg'
    name: bullOakEventStoreNugets
  

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
    # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: +tceHEN4n1HCeAOyBGT3/7PJMmGGv9LPcLN38Q0hNJpJS6C+h3PyCt8wxSwe/LwZ
    skip_symbols: false 
    artifact: /.*\.nupkg/ 

# scripts to run after deployment
after_deploy:
  - ps: |
        Write-Output "APPVEYOR_BUILD_VERSION = $APPVEYOR_BUILD_VERSION"
        Write-Output "env.APPVEYOR_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION"
        Write-Output "APPVEYOR_BUILD_NUMBER = $APPVEYOR_BUILD_NUMBER"
        Write-Output "env.APPVEYOR_BUILD_NUMBER = $env:APPVEYOR_BUILD_NUMBER"
        Write-Output "APPVEYOR_PULL_REQUEST_NUMBER = $APPVEYOR_PULL_REQUEST_NUMBER"
        Write-Output "env.APPVEYOR_PULL_REQUEST_NUMBER = $env:APPVEYOR_PULL_REQUEST_NUMBER"
        
        $postParams = @{ value1 = "BullOak.Repositories.EntityFramework"; value2 = "$env:standard_version"; value3="https://www.nuget.org/packages/BullOak.Repositories.EntityFramework/"  }
        Invoke-WebRequest -Uri https://maker.ifttt.com/trigger/bo_release/with/key/kSg0JPLZLcht1NDoihgjW -Method POST -Body $postParams

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
